WIP: fetch all forms from Survey CTO and their schemas
hikaya-io/connectors pull request #23
Opened 2021-02-05 18:16 UTC by TAnas0

# Work In Progress
## What is the Purpose?
Currently, the format/schema of the forms is hardcoded as an environment variable.
The goal is to dynamically get all the forms and their schemas from a SurveyCTO instance.

## What was the approach?
Work In Progress

## Are there any concerns to addressed further before or after merging this PR?
Work In Progress

## Mentions?
@sannleen @michaelbukachi 

## Issue(s) affected?
None

2021-02-07 23:42 UTC, amosnjoroge requested changes
Check the comments I have made

2021-02-07 23:42 UTC, amosnjoroge commented on surv_forms.md
> +- `statuses`: ¿What do they stand for?
This is the status of each submission, by default it is `approved` while other available statuses are `pending` and `rejected`

2021-02-07 23:42 UTC, amosnjoroge commented on surv_forms.md
> +- `unique_column`: ¿Is it really unique? ¿How does it differ from `form_id` above?
This is the primary key that will be unique for each submission and will be used when saving the data to the db

2021-02-07 23:42 UTC, amosnjoroge commented on surv_forms.md
> +¿Can a field have subfields?
Since we are using the wide format of data export I believe no field will have a subfield. checkout https://docs.surveycto.com/05-exporting-and-publishing-data/01-overview/09.data-format.html to understand how the data is exported

2021-02-07 23:42 UTC, amosnjoroge commented on DAGs/pull_survey_cto_data.py
> +            f'https://{SURV_SERVER_NAME}.surveycto.com/forms/{title}/workbook/export/load?includeFormStructureModel=true&submissionsPattern=all&fieldsPattern=all&fetchInBatches=true&includeDatasets=t
replace the timestap `t=1612193019966` with each forms created date

2021-02-07 23:42 UTC, amosnjoroge commented on DAGs/pull_survey_cto_data.py
> +    get_forms_ids()  # For Debugging purposes
The `get_forms_ids()`  should return `SURV_FORMS`
`SURV_FORMS = get_forms_ids()`

2021-02-08 22:05 UTC, TAnas0 commented on surv_forms.md
> +¿Can a field have subfields?
So on this, am I supposed to "flatten" all the fields? Because for now, I am keeping their nested format where a `Field` can have an attribute `children` composed of an array of `Field` s @sannleen

2021-02-09 07:49 UTC, amosnjoroge commented on surv_forms.md
> +¿Can a field have subfields?
@TAnas0 Yes, I think the best approach is to flatten all the fields. Ideally we are going to pick all children that are not of type `group`.

2021-02-25 12:57 UTC, TAnas0 commented
Closed in favor of https://github.com/hikaya-io/connectors/pull/25

2021-02-25 12:57 UTC, closed without merging