Improve logging for the DAGs
hikaya-io/connectors pull request #8
Opened 2020-11-06 11:20 UTC by TAnas0

## What is the Purpose?
- Improve the logging of the DAGs
- Add the `.github` template files for bugs, features and pull requests

## What was the approach?
- Instantiated an Airflow logger (https://stackoverflow.com/a/59541449/4017403) in the `utils.py` file and used it in the DAGs
- Added Github bug, feature and PR templates

## Are there any concerns to addressed further before or after merging this PR?
None

## Mentions?
@sannleen 

## Issue(s) affected?
Fix #12

2020-11-06 13:28 UTC, JumaKahiga commented on DAGs/helpers/utils.py
> +logger = logging.getLogger("airflow.task")
I would consider this an anti-pattern. Why not have `logger = logging.getLogger(__name__)` in every module.?

2020-11-06 13:28 UTC, JumaKahiga commented on DAGs/helpers/utils.py
> +        logger.error('clean_key_field method')
Consider `logger.exception()` so that you get the traceback included in the logs.

2020-11-10 12:36 UTC, TAnas0 commented on DAGs/helpers/utils.py
> +logger = logging.getLogger("airflow.task")
@JumaKahiga I, on the other hand, considered having this `logger` variable in every DAG a redundancy, and thought about refactoring it.
Why is this an anti-pattern and why is your suggested approach better?

2020-11-10 12:36 UTC, TAnas0 commented on DAGs/helpers/utils.py
> +        logger.error('clean_key_field method')
I ended up removing this specific line, but you are right. Using `logger.exception` is better. Problem is there is no proper exceptions handling (`try/catch` block at least) where we can use `logger.exception`. This is also something we should add to the DAGs.

2020-11-10 15:05 UTC, JumaKahiga commented on DAGs/helpers/utils.py
> +logger = logging.getLogger("airflow.task")
1. I consider it a better practice because it is what the Python [docs](https://docs.python.org/3/howto/logging.html#logging-advanced-tutorial) recommend. See excerpt:
```
A good convention to use when naming loggers is to use a module-level logger, in each module which uses logging, named as follows:

logger = logging.getLogger(__name__)

This means that logger names track the package/module hierarchy, and it’s intuitively obvious where events are logged just from the logger name.
```

2. As you scale, you'd rather each module owns its logger, which can be modified as need be instead of a common one.

2021-02-01 17:09 UTC, ninetteadhikari commented
@michaelbukachi for your review

2021-02-04 00:30 UTC, michaelbukachi requested changes
@TAnas0 Do you mind resolving the merge conflicts?

2021-02-04 15:42 UTC, TAnas0 commented
@michaelbukachi Done! :+1:

2021-02-04 21:10 UTC, michaelbukachi approved these changes

2021-02-04 21:11 UTC, michaelbukachi commented
@TAnas0 I think we can merge this.

2021-02-04 21:48 UTC, merged